#!/bin/bash
# Generated by dsh-super-injector dev_scaffold_plugin (P1.2 扩展：client/打包依赖链接补齐，
# 干净 checkout 可一次 build 到 client bundle；host 依赖链接语义不变).
# Build: compile src/ → lib/ with the dsh checkout's tsc.
# Requires DSH_CHECKOUT pointing at a dsh source checkout (auto-probe below).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# DSH_CHECKOUT 探测：环境变量 → 常见路径（home 下 dsh-harness）
CHECKOUT="${DSH_CHECKOUT:-}"
if [ -z "$CHECKOUT" ]; then
  for candidate in "$HOME/dsh-harness" "$HOME/dsh" "$HOME/.dsh/dsh-harness"; do
    if [ -d "$candidate/packages" ]; then CHECKOUT="$candidate"; break; fi
  done
fi
if [ -z "$CHECKOUT" ] || [ ! -d "$CHECKOUT/packages" ]; then
  echo "build: cannot locate the dsh checkout (set DSH_CHECKOUT)" >&2
  exit 1
fi

TSC="$CHECKOUT/node_modules/.bin/tsc"
if [ ! -x "$TSC" ] && [ ! -f "$TSC.cmd" ]; then
  echo "build: tsc not found at $TSC" >&2
  exit 1
fi

# 链接一个 checkout 相对路径（target 先 realpath，避免 checkout 顶层自身是 pnpm symlink）。
link_pkg() {
  local target="$CHECKOUT/$2"
  if [ ! -e "$target" ]; then
    echo "build: dependency target missing: $target" >&2
    exit 1
  fi
  node -e "
    const fs = require('fs');
    const path = require('path');
    const link = path.resolve(process.argv[1]);
    const target = fs.realpathSync(path.resolve(process.argv[2]));
    fs.rmSync(link, { recursive: true, force: true });
    fs.mkdirSync(path.dirname(link), { recursive: true });
    fs.symlinkSync(target, link, process.platform === 'win32' ? 'junction' : 'dir');
  " "node_modules/$1" "$target"
}

# 链接一个 pnpm store 包（如 react / @types/react）。name 形如 'react' 或 '@types/react'。
link_store_pkg() {
  local name="$1"
  if [ -e "$CHECKOUT/node_modules/$name" ]; then
    link_pkg "$name" "node_modules/$name"
    return
  fi
  local store_key="${name//\//+}"
  local store
  store=$(find "$CHECKOUT/node_modules/.pnpm" -maxdepth 1 -type d -iname "${store_key}@*" 2>/dev/null | head -1)
  local target="$store/node_modules/$name"
  if [ -z "$store" ] || [ ! -d "$target" ]; then
    echo "build: pnpm store package missing: $name" >&2
    exit 1
  fi
  node -e "
    const fs = require('fs');
    const path = require('path');
    const link = path.resolve(process.argv[1]);
    const target = fs.realpathSync(path.resolve(process.argv[2]));
    fs.rmSync(link, { recursive: true, force: true });
    fs.mkdirSync(path.dirname(link), { recursive: true });
    fs.symlinkSync(target, link, process.platform === 'win32' ? 'junction' : 'dir');
  " "node_modules/$name" "$target"
}

echo "=== Linking build dependencies (checkout: $CHECKOUT) ==="
mkdir -p node_modules/@deepseek-ai
node -e "const fs=require('fs');fs.rmSync('node_modules/@standard-schema',{recursive:true,force:true})"
link_pkg cordis vendor/cordis
node -e "
  const fs = require('fs');
  const path = require('path');
  fs.rmSync('node_modules/@deepseek-ai/cordis', { recursive: true, force: true });
  fs.symlinkSync(path.resolve('node_modules/cordis'), path.resolve('node_modules/@deepseek-ai/cordis'), process.platform === 'win32' ? 'junction' : 'dir');
"
link_pkg cosmokit vendor/cosmokit
link_pkg schemastery vendor/schemastery
# settings 注册（设置 UI 壳 host 半边；SettingsProvider.installSection）
link_pkg @deepseek-ai/dsh-settings packages/settings/settings
# 事件面接线（P1：H1/H7 订阅类型面 + dsh-session d.ts 解析链）
link_pkg @deepseek-ai/dsh-session packages/core/session
# P6：改史端口（H4/H5 共享事务原语；dsh-compaction 提供 compaction/* 类型与配对平衡守卫）
link_pkg @deepseek-ai/dsh-commands packages/interaction/commands
link_pkg @deepseek-ai/dsh-compaction packages/compaction/compaction
# P19a：H2 步准入端口类型面（agent/pre-step waterfall；type-only peerDep）
link_pkg @deepseek-ai/dsh-agent packages/core/agent
link_pkg @deepseek-ai/dsh-llm packages/llm/llm
# P4：技能目录端口（ctx.skills 官方注册表；只 import dsh-skill，不手写文件扫描）
link_pkg @deepseek-ai/dsh-skill packages/skill/skill
# P7：工具端口（H6 tools/execute + post-execute）
link_pkg @deepseek-ai/dsh-tools packages/core/tools
# P17b：盘上取真端口（H15 ctx.fs 抽象服务；本地后端由部署装配，端口只依赖抽象面）
link_pkg @deepseek-ai/dsh-fs packages/fs/fs
link_pkg @deepseek-ai/dsh-brand packages/util/brand
link_pkg @deepseek-ai/dsh-util-values packages/util/values
link_pkg @deepseek-ai/dsh-scope packages/core/scope
link_pkg @deepseek-ai/dsh-session-persistence packages/session/session-persistence
# P3：storageDomain 持久面依赖（host 侧只 import dsh-storage-domain；dsh-storage 为域层内部依赖）
link_pkg @deepseek-ai/dsh-storage packages/storage/storage
link_pkg @deepseek-ai/dsh-storage-domain packages/storage/storage-domain
# @types/node（编译类型；checkout 自带）
link_pkg @types/node node_modules/@types/node

# P1.2：client typecheck/tsdown 依赖链接补齐（此前依赖历史手工 junction，干净归档构建失败）。
link_pkg @deepseek-ai/dsh-api-remotes packages/api/remotes
link_pkg @deepseek-ai/dsh-client-store packages/client/store
link_pkg @deepseek-ai/dsh-client-ui-renderer packages/client/ui-renderer
link_pkg @deepseek-ai/dsh-client-ui-settings packages/client/ui-settings
link_pkg @deepseek-ai/dsh-client-ui-settings-plugins packages/client/ui-settings-plugins
link_pkg @deepseek-ai/dsh-client-ui-slots packages/client/ui-slots
# P14a：星标按钮 type-only 槽位声明与标准会话 props 依赖（不新增运行时 peerDep）。
link_pkg @deepseek-ai/dsh-client-ui-conversation packages/client/ui-conversation
link_pkg @deepseek-ai/dsh-client-ui-session packages/client/ui-session
# P14b1：星标 Connection RPC 桥类型锚（源子路径 type-only；不级联 webserver/credentials/attachment）。
link_pkg @deepseek-ai/dsh-client-connection packages/client/connection
link_pkg tsdown node_modules/tsdown
link_store_pkg react
link_store_pkg @types/react
link_store_pkg zod

STD_SCHEMA=$(find "$CHECKOUT/node_modules/.pnpm" -maxdepth 1 -type d -iname '@standard-schema+spec@*' 2>/dev/null | head -1)
if [ -n "$STD_SCHEMA" ]; then
  node -e "
    const fs = require('fs');
    const path = require('path');
    fs.rmSync('node_modules/@standard-schema', { recursive: true, force: true });
    fs.mkdirSync('node_modules/@standard-schema', { recursive: true });
    fs.symlinkSync(path.resolve(process.argv[1]), path.resolve('node_modules/@standard-schema/spec'), process.platform === 'win32' ? 'junction' : 'dir');
  " "$STD_SCHEMA/node_modules/@standard-schema/spec"
fi

echo "=== Compiling src → lib ==="
"$TSC" -p tsconfig.json
echo "=== Build complete (host) ==="

# client bundle（tsdown；存在 client/ 目录时执行——注入器/官方双形态同此约定）
if [ -d "$ROOT/client" ]; then
  echo "=== Building client bundle (tsdown) ==="
  if command -v tsdown >/dev/null 2>&1; then
    tsdown
  elif [ -x "$CHECKOUT/node_modules/.bin/tsdown" ]; then
    "$CHECKOUT/node_modules/.bin/tsdown"
  elif [ -x "$CHECKOUT/node_modules/.bin/tsdown.cmd" ]; then
    "$CHECKOUT/node_modules/.bin/tsdown.cmd"
  else
    echo "build: tsdown not found in checkout—client bundle skipped (run build:client manually)" >&2
  fi
  echo "=== Build complete (client) ==="
fi
