#!/bin/bash
# Generated by dsh-super-injector dev_scaffold_plugin.
# Build: compile src/ → lib/ with the dsh checkout's tsc.
# Requires DSH_CHECKOUT pointing at a dsh source checkout (auto-probe below).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# DSH_CHECKOUT 探测：环境变量 → 常见路径（home 下 dsh-harness）
CHECKOUT="${DSH_CHECKOUT:-}"
if [ -z "$CHECKOUT" ]; then
  for candidate in "$HOME/dsh-harness" "$HOME/dsh" "$HOME/.dsh/dsh-harness"; do
    if [ -d "$candidate/packages" ]; then CHECKOUT="$candidate"; break; fi
  done
fi
if [ -z "$CHECKOUT" ] || [ ! -d "$CHECKOUT/packages" ]; then
  echo "build: cannot locate the dsh checkout (set DSH_CHECKOUT)" >&2
  exit 1
fi

TSC="$CHECKOUT/node_modules/.bin/tsc"
if [ ! -x "$TSC" ] && [ ! -f "$TSC.cmd" ]; then
  echo "build: tsc not found at $TSC" >&2
  exit 1
fi

link_pkg() {
  local target="$CHECKOUT/$2"
  if [ ! -e "$target" ]; then
    echo "build: dependency target missing: $target" >&2
    exit 1
  fi
  node -e "
    const fs = require('fs');
    const path = require('path');
    const link = path.resolve(process.argv[1]);
    const target = path.resolve(process.argv[2]);
    fs.rmSync(link, { recursive: true, force: true });
    fs.mkdirSync(path.dirname(link), { recursive: true });
    fs.symlinkSync(target, link, process.platform === 'win32' ? 'junction' : 'dir');
  " "node_modules/$1" "$target"
}

echo "=== Linking build dependencies (checkout: $CHECKOUT) ==="
mkdir -p node_modules/@deepseek-ai
node -e "const fs=require('fs');fs.rmSync('node_modules/@standard-schema',{recursive:true,force:true})"
link_pkg cordis vendor/cordis
node -e "
  const fs = require('fs');
  const path = require('path');
  fs.rmSync('node_modules/@deepseek-ai/cordis', { recursive: true, force: true });
  fs.symlinkSync(path.resolve('node_modules/cordis'), path.resolve('node_modules/@deepseek-ai/cordis'), process.platform === 'win32' ? 'junction' : 'dir');
"
link_pkg cosmokit vendor/cosmokit
link_pkg schemastery vendor/schemastery
link_pkg @deepseek-ai/dsh-llm packages/llm/llm
# 任务记忆域依赖（类型导入）：session 投影 / session / 压缩服务定义
link_pkg @deepseek-ai/dsh-session-projection packages/session/session-projection
link_pkg @deepseek-ai/dsh-session packages/core/session
link_pkg @deepseek-ai/dsh-compaction packages/compaction/compaction
link_pkg @deepseek-ai/dsh-agent packages/core/agent
# settings 注册（GUI 配置卡片 host 半边；installSettingsSection）
link_pkg @deepseek-ai/dsh-settings packages/settings/settings
# 任务记忆域依赖（类型导入）：todo 事件所有权在 dsh-tool-todo，
# 需载入其对 SessionEventMap 的声明合并，使 'todo/write' 类型可解析。
link_pkg @deepseek-ai/dsh-tool-todo packages/todo/tool-todo
# zod（投影 stateSchema 运行时依赖；从 checkout 的 pnpm store 定位）
ZOD_DIR=$(find "$CHECKOUT/node_modules/.pnpm" -maxdepth 1 -type d -iname 'zod@*' 2>/dev/null | head -1)
if [ -n "$ZOD_DIR" ]; then
  node -e "
    const fs = require('fs');
    const path = require('path');
    fs.rmSync('node_modules/zod', { recursive: true, force: true });
    fs.symlinkSync(path.resolve(process.argv[1], 'node_modules/zod'), path.resolve('node_modules/zod'), process.platform === 'win32' ? 'junction' : 'dir');
  " "$ZOD_DIR"
else
  echo "build: zod not found in checkout pnpm store" >&2
fi
# @types/node（编译类型；checkout 自带）
link_pkg @types/node node_modules/@types/node

STD_SCHEMA=$(find "$CHECKOUT/node_modules/.pnpm" -maxdepth 1 -type d -iname '@standard-schema+spec@*' 2>/dev/null | head -1)
if [ -n "$STD_SCHEMA" ]; then
  node -e "
    const fs = require('fs');
    const path = require('path');
    fs.rmSync('node_modules/@standard-schema', { recursive: true, force: true });
    fs.mkdirSync('node_modules/@standard-schema', { recursive: true });
    fs.symlinkSync(path.resolve(process.argv[1]), path.resolve('node_modules/@standard-schema/spec'), process.platform === 'win32' ? 'junction' : 'dir');
  " "$STD_SCHEMA/node_modules/@standard-schema/spec"
fi

echo "=== Compiling src → lib ==="
"$TSC" -p tsconfig.json
echo "=== Build complete (host) ==="

# client bundle（tsdown；存在 client/ 目录时执行——注入器/官方双形态同此约定）
if [ -d "$ROOT/client" ]; then
  echo "=== Building client bundle (tsdown) ==="
  if command -v tsdown >/dev/null 2>&1; then
    tsdown
  elif [ -x "$CHECKOUT/node_modules/.bin/tsdown" ]; then
    "$CHECKOUT/node_modules/.bin/tsdown"
  elif [ -x "$CHECKOUT/node_modules/.bin/tsdown.cmd" ]; then
    "$CHECKOUT/node_modules/.bin/tsdown.cmd"
  else
    echo "build: tsdown not found in checkout—client bundle skipped (run build:client manually)" >&2
  fi
  echo "=== Build complete (client) ==="
fi
